/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated.recommendations'
import { Route as AuthenticatedForecastRouteImport } from './routes/_authenticated.forecast'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated.admin.students'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated.admin.logs'
import { Route as AuthenticatedAdminForecastsRouteImport } from './routes/_authenticated.admin.forecasts'
import { Route as AuthenticatedAdminStudentsUserIdRouteImport } from './routes/_authenticated.admin.students.$userId'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedForecastRoute = AuthenticatedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminForecastsRoute =
  AuthenticatedAdminForecastsRouteImport.update({
    id: '/forecasts',
    path: '/forecasts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsUserIdRoute =
  AuthenticatedAdminStudentsUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/roadmap': typeof RoadmapRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/admin/forecasts': typeof AuthenticatedAdminForecastsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/students/$userId': typeof AuthenticatedAdminStudentsUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/roadmap': typeof RoadmapRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/admin/forecasts': typeof AuthenticatedAdminForecastsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/students/$userId': typeof AuthenticatedAdminStudentsUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/roadmap': typeof RoadmapRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/forecast': typeof AuthenticatedForecastRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/admin/forecasts': typeof AuthenticatedAdminForecastsRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/_authenticated/admin/students/$userId': typeof AuthenticatedAdminStudentsUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/roadmap'
    | '/admin'
    | '/dashboard'
    | '/forecast'
    | '/recommendations'
    | '/admin/forecasts'
    | '/admin/logs'
    | '/admin/students'
    | '/admin/students/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/roadmap'
    | '/admin'
    | '/dashboard'
    | '/forecast'
    | '/recommendations'
    | '/admin/forecasts'
    | '/admin/logs'
    | '/admin/students'
    | '/admin/students/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/roadmap'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/forecast'
    | '/_authenticated/recommendations'
    | '/_authenticated/admin/forecasts'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/students/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/forecasts': {
      id: '/_authenticated/admin/forecasts'
      path: '/forecasts'
      fullPath: '/admin/forecasts'
      preLoaderRoute: typeof AuthenticatedAdminForecastsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students/$userId': {
      id: '/_authenticated/admin/students/$userId'
      path: '/$userId'
      fullPath: '/admin/students/$userId'
      preLoaderRoute: typeof AuthenticatedAdminStudentsUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
  }
}

interface AuthenticatedAdminStudentsRouteChildren {
  AuthenticatedAdminStudentsUserIdRoute: typeof AuthenticatedAdminStudentsUserIdRoute
}

const AuthenticatedAdminStudentsRouteChildren: AuthenticatedAdminStudentsRouteChildren =
  {
    AuthenticatedAdminStudentsUserIdRoute:
      AuthenticatedAdminStudentsUserIdRoute,
  }

const AuthenticatedAdminStudentsRouteWithChildren =
  AuthenticatedAdminStudentsRoute._addFileChildren(
    AuthenticatedAdminStudentsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminForecastsRoute: typeof AuthenticatedAdminForecastsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminForecastsRoute: AuthenticatedAdminForecastsRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedForecastRoute: typeof AuthenticatedForecastRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedForecastRoute: AuthenticatedForecastRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
